#Instructions
#Clash of Clans, Fruit Ninja Classic, and Minecraft: Pocket Edition are classified as games. We've provided their lists in the code editor. Group these games into a single list of lists.

#1-Create a new list of lists that stores the lists (rows) for the applications that are games, Clash of Clans, Fruit Ninja Classic, and Minecraft: Pocket Edition. Assign the output to a variable named games_apps.
#Use the variable names for each list generated by the display code in the code editor.

row_1 = ['Facebook', 0.0, 'USD', 2974676, 3.5]
row_2 = ['Instagram', 0.0, 'USD', 2161558, 4.5]
row_3 = ['Clash of Clans', 0.0, 'USD', 2130805, 4.5]
row_4 = ['Fruit Ninja Classic', 1.99, 'USD', 698516, 4.5]
row_5 = ['Minecraft: Pocket Edition', 6.99, 'USD', 522012, 4.5]

games_apps = [row_3, row_4, row_5]
